Motd: '&f&M|---------[&4CrazyPvP&f&M]---------|'
StatusMotd: '&4CrazyPvP &cVenha Treinar Seu PvP &41.8.X - 1.7.X'
NomeServer: '&4CrazyPvP'
MensagemAutomatica1: '&2Servidor em beta '
MensagemAutomatica2: '&2Divulgue O Nosso Servidor '
MensagemAutomatica3: '&4Nao Use Hack '
MensagemAutomatica4: '&bCompre vip e ajude o servidor!'
MensagemAutomatica5: '&cDuvidas ? /ajuda !'
MensagemAplicar1: '&DFormulario Para Trial: &7EM-BREVE'
MensagemYoutuber1: '&bPara se tornar YT No Servidor Necessita-se de 300 Subs + Video No Servidor e 250 likes'
MensagemYoutuber2: '&cPara se tornar Pro Necessita-se de 240 Subs + Video No Servidor e 108 Likes'
MensagemYoutuber3: '&cPara se tornar Spro Necessita-se de 102 Subs + Video No Servidor e 56 Likes'

